### ISSUE TITLE
dgl-devday@request-nb.mxnet.io doesn't exist

### ISSUE THREAD

**Issue by ke-ke9** [dglai/WWW20-Hands-on-Tutorial#3]
Please send an email to dgl-devday@request-nb.mxnet.io
You’ll get two replies in a few minutes. The second email contains a URL of

I send an email and received:
```
收件人邮件地址（dgl-devday@request-nb.mxnet.io）不存在，邮件无法送达。 
host request-nb.mxnet.io[54.240.248.234] said: 550 5.1.1 Requested action not taken: mailbox unavailable (in reply to RCPT TO command)
```

**Comment by VoVAllen** [comment]
Hi,

This is for the live audiences in WWW 2020. Therefore instances are not prepared yet.
